# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# - title: Your awesome title
email: your-email@domain.com

# - avatar: han-solo.jpg
full_# - name: Han Solo
# - bio: Swindler. Scoundrel. Bad Ass.

# Build settings
# - markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: assets/stylesheets
  style: :compressed

# Output
# - permalink: /:year/:month/:slug/

title: "Andrew Henry"
tagline: ""
description: "Powered by <a href=\"http://micro.blog/\">Micro.blog</a>."
credits: "Powered by <a href=\"http://micro.blog/\">Micro.blog</a>."
baseurl: ""
url: "http://andymitchhank.com"
markdown: "kramdown"
username: "andymitchhank"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Andrew Henry"
name: "Andrew Henry"
gravatar_hash: "9dcfb2cd6e8f574d568dba79bdf6aa94"
avatar: "https://www.gravatar.com/avatar/9dcfb2cd6e8f574d568dba79bdf6aa94?s=160"
full_name: "Andrew Henry"
bio: ""
twitter_username: "andymitchhank"
github_username: "andymitchhank"
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Indiana-Starke"