email: your-email@domain.com

exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: assets/stylesheets
  style: :compressed

title: "Andrew Henry"
tagline: ""
description: "Follow <a href=\"https://micro.blog/andymitchhank\">@andymitchhank on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/andymitchhank\">@andymitchhank on Micro.blog</a>."
baseurl: ""
url: "http://andymitchhank.com"
markdown: "kramdown"
username: "andymitchhank"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Andrew Henry"
name: "Andrew Henry"
gravatar_hash: "9dcfb2cd6e8f574d568dba79bdf6aa94"
avatar: "https://micro.blog/andymitchhank/avatar.jpg"
full_name: "Andrew Henry"
bio: ""
twitter_username: "andymitchhank"
github_username: "andymitchhank"
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Indiana-Starke"
site_id: ["SITE_ID"]